### ISSUE TITLE
Systemd stops Service when started by timer

### ISSUE THREAD

**Issue by jstenvall-ducksify** [0x0I/ansible-role-systemd#53]
## Description

A timer starts an `ansible` playbook that in turn updates the definitions of `systemd` unit files. When being executed, the role ensures that the running state conforms to the value of `unit_item.state` or `_default_unit_state`. Since it is started by a systemd timer is not supposed to be enabled, hence the service is shutdown.

Here's an example output from journald:

    ...
    Dec 02 15:47:35 testserver ansible-systemd[899197]: Invoked with name=ansible_run.timer state=started enabled=True daemon_reload=False daemon_reexec=False scope=system no_block=False force=None masked=None
    Dec 02 15:47:35 testserver sudo[899195]: pam_unix(sudo:session): session closed for user root
    Dec 02 15:47:35 testserver run_ansible.sh[886121]: ok: [testserver.test.com] => (item=ansible_run.timer)
    ...
    Dec 02 15:47:35 testserver ansible-systemd[899227]: Invoked with name=ansible_run.service state=stopped enabled=False daemon_reload=False daemon_reexec=False scope=system no_block=False force=None masked=None
    Dec 02 15:47:35 testserver systemd[1]: Stopping Service Run Ansible...
    Dec 02 15:47:35 testserver sudo[899225]: pam_unix(sudo:session): session closed for user root
    Dec 02 15:47:35 testserver run_ansible.sh[886121]: Terminated
    Dec 02 15:47:35 testserver systemd[1]: ansible_run.service: Main process exited, code=killed, status=15/TERM
    ...

The unit does not contain a value for the state, it is set to the value of `_default_unit_enabled`, so the service must be stopped.

## Remediation

Not sure how to fix this. Maybe a flag saying that the state is managed (by a timer) or not.

```yaml
unit_config:
  - name: "Test Service"
    manage_state: false
    Unit:
      Description: Service Test
    Service:
      User: test_user
      Group: test_user
      ExecStart: /usr/bin/ls /etc/fstab
    Install:
      WantedBy: multi-user.target
  - name: "Test Timer"
    type: timer
    enabled: true
    state: started
    Unit:
      Description: Timer Test
    Timer:
      OnCalendar: "*-*-* 4:00:00"
      Unit: "test_service.service"
    Install:
      WantedBy: timers.target
```

This is the modified launch.yml:

```yaml
- name: Activate configured Systemd units
  become: true
  when: unit_config is defined and unit_config|length > 0 and (unit_item.type is not defined or unit_item.type != 'conf')
  vars:
    _this_unit_state: "{{ omit if (unit_item.manage_state is defined and not unit_item.manage_state) else _default_unit_state }}"
  systemd:
    name: "{{ unit_item.name }}.{{ unit_item.type | default(_default_unit_type) }}"
    state: "{{ unit_item.state | default(_this_unit_state) }}"
    enabled: "{{ unit_item.enabled | default(_default_unit_enabled) }}"
  loop: "{{ unit_config }}"
  loop_control:
    loop_var: unit_item
    label: "{{ unit_item.name }}.{{ unit_item.type|default(_default_unit_type) }}"
  tags:
    - launch
```

The hash `unit_item` either contains a boolean flag `manage_state`, or not.

What do you think?
